from app.routers.auth import router as auth
from app.routers.users import router as users
from app.routers.cms import router as cms
from app.routers.studies import router as studies
from app.routers.reports import router as reports
from app.routers.comments import router as comments
from app.routers.billing import router as billing
from app.routers.pacs import router as pacs
from app.routers.search import router as search
from app.routers.analytics import router as analytics
from app.routers.organizations import router as organizations
from app.routers.patients import router as patients
from app.routers.notes import router as notes
from app.routers.attachments import router as attachments
from app.routers.audit import router as audit
from app.routers.locks import router as locks
from app.routers.verification import router as verification
from app.routers.templates import router as templates
from app.routers.branding import router as branding
from app.routers.sharing import router as sharing
from app.routers.follow_ups import router as follow_ups
from app.routers.print_history import router as print_history
from app.routers.realtime import router as realtime
